import Navbar from "@/app/components/navbar";
import Footer from "./components/footer";

import "./globals.css";

export const metadata = {
  title: "Mallu Trigueiro - Fotografia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
